### ISSUE TITLE
Non-Quantized Model Breaks Detector

### ISSUE THREAD

**Issue by chrisgilldc** [snowzach/doods2#4] opened 2022-01-03 02:54 UTC
Good evening!

Giving this a shot and running into the first clear error. Using the Yolov5-built and exported to TF-Lite model, I'm getting the following:

```INFO:     10.0.2.100:52310 - "POST /detect HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/doods/api.py", line 27, in detect
    detect_response = self.doods.detect(detect_request)
  File "/opt/doods/doods.py", line 108, in detect
    ret = detector.detect(image)
  File "/opt/doods/detectors/tflite.py", line 57, in detect
    self.input_data = (np.float32(self.input_data) - input_mean) / input_std
AttributeError: 'TensorflowLite' object has no attribute 'input_data'```

Note the model is not quantized - I probably should quantize it, but I'm not sure how to actually do that yet. :-P

If I have HA hit the 'default' detector which uses a quantized TFLite model, no error.

**Comment by snowzach** [comment] 2022-01-04 03:11
Basically the issue is that different Tensorflow models have different inputs and outputs. For the most part the object detection models are all the same inputs and outputs. On all of the tflite models I use the input tensor is called `input_data`. The model you are using does not have a tensor with that name so DOODS doesn't know where to input the image data. Do you have any python sample code that works with this model?

**Comment by snowzach** [comment] 2022-01-04 13:44
Is this what you are using? https://github.com/ultralytics/yolov5 It might be easier to add support for that than to use the tflite model? Send me a link to the model you are trying to use if you can.

**Comment by chrisgilldc** [comment] 2022-01-04 13:52
It is. It's my first model, so I may very well be doing it wrong. The TFlite export seems to work, but I'm not yet testing it outside of Colab.
I can shoot you the notebook, model, etc, and take my own shot at testing the model with the TF lite python library

**Comment by snowzach** [comment] 2022-01-07 03:14
Yeah send over whatever and I'll try it.

**Comment by snowzach** [comment] 2022-01-10 04:51
I added support for PyTorch. You wanna just use that instead? See the README. You can use Yolo directly now.

**Comment by chrisgilldc** [comment] 2022-01-15 11:26
Morning! Got a working hubconf for the model and it's loading now, so big thanks. I still need to figure out how to slim down my custom model - it's currently a whopping 167 megs - but looks like it loads and works.

**Comment by snowzach** [comment] 2022-01-15 13:36
Awesome! Glad to hear. Going to close this, reopen if it's an issue.

**Closed by snowzach** 2022-01-15 13:36 UTC

**Comment by chrisgilldc** [comment] 2022-01-15 13:39
Sounds good. Appears I'm having an issue running actual inference, but pretty sure that's an issue with my actual model construction 

-- 
  Chris Gill
  ***@***.***
  "War is the remedy our our enemies have chosen, and I say let us give them all they want."
  - William Tecumseh Sherman
