### ISSUE TITLE
Problems with detection areas and multiple image_processing pipelines

### ISSUE THREAD

**Issue by eugemaf** [snowzach/doods2#22] opened 2022-01-19 18:50 UTC
I’m facing some problems with a configuration with 2 image_processing pipelines activated with doods2, using the same detector. 
The problem is related to the detection area definition: if I define a  detection area for each image_processing only the first one works, while the other pipeline is stopped (no detection at all on the second image_processing pipeline).

This is my configuration (extract): 

```
image_processing:
  - platform: doods
    scan_interval: 2
    url: !secret DOODS_url 
    timeout: 10
    detector: mydetector
    source:
      - entity_id: camera.cam_one
    file_out:
      - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
    area:
      top:    0.3
      left:   0.05
      bottom: 1.0
      right:  0.95 
      
  - platform: doods
    scan_interval: 2
    url: !secret DOODS_url
    timeout: 10
    detector: mydetector
    source:
      - entity_id: camera.cam_two
    file_out:
      - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
    confidence: 30
    area:
      top:    0.2
      left:   0.1
      bottom: 0.9
      right:  0.95 

    labels:
    - name: MYLABEL_1
    - name: MYLABEL_2
    - name: MYLABEL_3

```

May be there is an error in the configuration file... but I cannot see it.

Anyway without any area definition the two pipelines work correctly.... (i.e. DOODS2 rocks!)

Thank you for your precious help!

**Comment by snowzach** [comment] 2022-01-21 02:38
Hmmm.. the first one doesn't have a confidence... It looks okay to me otherwise. They are processed as completely separate entities so the config of one shouldn't effect the config of the other unless there's something wrong with hass.. Not really sure..

**Comment by snowzach** [comment] 2022-01-21 02:38
maybe disable one at a time and see if the other one works.

**Comment by eugemaf** [comment] 2022-01-21 10:26
I enabled confidence also on the other pipeline in order to have a similar configuration: with this configuration it works without defined areas and quite seldom with both areas defined (I've had to wait a while for seeing it).
I observed also that the images defined in `file_out` are not regularly written, maybe sometime some internal exceptions in putText occur that force the detect function to return before writing. May be this the reason?

**Comment by snowzach** [comment] 2022-01-21 13:33
If there's an exception, it should show up in the logs. See anything in there?

**Comment by eugemaf** [comment] 2022-01-21 15:29
no, nothing, also enabling logging debug.

**Comment by snowzach** [comment] 2022-01-27 03:39
I just checked... it's working.. I think the issue is that your areas are excluding whatever it is you're detecting. 
If you want to detect an area any only care that the detection is anywhere in the box set the covers field to false.
```
    area:
      top:    0.2
      left:   0.1
      bottom: 0.9
      right:  0.95 
      covers: false
```

**Comment by snowzach** [comment] 2022-01-29 02:02
Closing this. Reopen if there's another issue.

**Closed by snowzach** 2022-01-29 02:02 UTC

**Comment by Nem0oo** [comment] 2022-02-15 05:10
I have a similar issue.
Whether I put 2 sources or duplicate the entire  doods platform conf the result is the same.
The second instance is not working.
When I call the service on the developer tools using Doods cameraTwo entity, the picture generated is always the one from the first camera on both output files.

`- platform: doods
  url: !secret doodsDockerURL
  detector: default
  scan_interval: 10000
  source:
    - entity_id: camera.cameraOne
  file_out: "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
  confidence: 30
  labels:
    - name: person
      confidence: 62

- platform: doods
  url: !secret doodsDockerURL
  detector: default
  scan_interval: 10000
  source:
    - entity_id: camera.cameraTwo
  file_out: "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
  confidence: 30
  labels:
    - name: person
      confidence: 62
`
